---
title: "Honest CIs: NSW example"
author: "Michal Kolesár"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: false
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Inference for Average Treatment Effects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include=FALSE, cache=FALSE}
library("knitr")
knitr::opts_knit$set(self.contained = FALSE)
knitr::opts_chunk$set(tidy = TRUE, collapse=TRUE, comment = "#>",
                      tidy.opts=list(blank=FALSE, width.cutoff=55))
```

The package `ATEHonest` implements honest inference for estimating average
treatment effects under unconfoundedness. Here we illustrate the use of the
package using NSW data.


The data is shipped with the package, as a data frame called `NSW`. First we
extract the design matrix, and the treatment and outcome vectors:

```{r}
library("ATEHonest")
X <- as.matrix(NSW[, 2:10])
## weight matrix
Ahalf <- diag(c(0.15, 0.6, 2.5, 2.5, 2.5, 0.5, 0.5, 0.1, 0.1))
d <- NSW$treated
y <- NSW$re78

## Compute matrix of distances between treated and control units
D0 <- distMat(X, Ahalf, method="manhattan", d)
```

TODO: finish
